#!/bin/bash

# Check the operating system
OS_NAME=$(uname -s)
OS_VERSION=""

if [[ "$OS_NAME" == "Linux" ]]; then
    if command -v lsb_release &>/dev/null; then
        OS_VERSION=$(lsb_release -rs)
    elif [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS_VERSION=$VERSION_ID
    fi
    # Tested on Ubuntu 22.04 (jammy) and 24.04 (noble). The host was upgraded
    # 22.04 → 24.04, which bumps the system toolchain to GCC 13 — fine because
    # the hardware SDKs build against the conda cross-compiler, not system GCC.
    if [[ "$OS_VERSION" != "22.04" && "$OS_VERSION" != "24.04" ]]; then
        echo "Warning: This script has only been tested on Ubuntu 22.04 and 24.04"
        echo "Your system is running Ubuntu $OS_VERSION."
        read -p "Do you want to continue anyway? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Installation cancelled."
            exit 1
        fi
    fi
else
    echo "Unsupported operating system: $OS_NAME"
    exit 1
fi

echo "Operating system check passed: $OS_NAME $OS_VERSION"

# Large PyPI wheels such as torch can exceed uv's default 30s timeout on
# slower links. Allow callers to override, but use a safer default for setup.
export UV_HTTP_TIMEOUT="${UV_HTTP_TIMEOUT:-300}"

# Resolve script directory so files can be referenced reliably
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
PROJECT_ROOT="$SCRIPT_DIR"

# Conda environment yaml file (canonical name)
CONDA_ENV_FILE="$SCRIPT_DIR/conda_environment.yaml"
if [[ ! -f "$CONDA_ENV_FILE" ]]; then
    echo "Error: conda environment yaml not found: $CONDA_ENV_FILE"
    exit 1
fi

# ── Conda environment creation ────────────────────────────────────────────────

create_environment() {
    local CONDA_CMD=$1
    local ENV_NAME=$2

    # Deactivate current environment if any (use conda deactivate for both conda and mamba)
    conda deactivate 2>/dev/null || true

    # Remove existing environment if it exists
    if $CONDA_CMD env list | grep -q "^$ENV_NAME "; then
        echo "Removing existing environment '$ENV_NAME'..."
        if ! $CONDA_CMD env remove -n "$ENV_NAME" -y; then
            echo "Error: Failed to remove existing environment '$ENV_NAME'."
            return 1
        fi
    fi

    # Create new environment from conda_environment.yaml
    if ! $CONDA_CMD env create -f "$CONDA_ENV_FILE" -n "$ENV_NAME"; then
        echo "Error: Failed to create $CONDA_CMD environment '$ENV_NAME' from: $CONDA_ENV_FILE"
        return 1
    fi

    echo "$CONDA_CMD environment '$ENV_NAME' created from: $CONDA_ENV_FILE"

    echo -e "[INFO] Created $CONDA_CMD environment named '$ENV_NAME'.\n"
    echo -e "\t\t1. To activate the environment, run:                $CONDA_CMD activate $ENV_NAME"
    echo -e "\t\t2. To install all dependencies, run:                bash $SCRIPT_NAME --install"
    echo -e "\t\t3. To deactivate the environment, run:              conda deactivate"
    echo -e "\n"
}

# ── Shared helpers for hardware installation ──────────────────────────────────

# Write sitecustomize.py that preloads conda's own copies of libraries the system
# also ships, at Python startup: libstdc++ (CXXABI_1.3.15 for GCC 14+ extensions
# like ARX5 / flexiv_rt) and FFmpeg 8 (so torchcodec uses conda's FFmpeg instead of
# silently falling back to the system's). The generated file explains both.
#
# Preloading rather than LD_LIBRARY_PATH is forced: grant_rt_scheduling below gives
# the interpreter cap_sys_nice, which puts it in secure-execution mode (AT_SECURE=1)
# where the kernel strips LD_LIBRARY_PATH from the environment outright. Verified on
# this host: getcap reports cap_sys_nice=ep and LD_LIBRARY_PATH reads as unset inside
# the process even when exported.
write_sitecustomize() {
    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"python{sys.version_info.major}.{sys.version_info.minor}")')"
    local SITE_DIR="${CONDA_PREFIX}/lib/${PY_VER}/site-packages"
    local TARGET="${SITE_DIR}/sitecustomize.py"

    # Version the file so adding a preloader actually reaches environments that
    # already have an older sitecustomize. (The previous guard matched on
    # "RTLD_GLOBAL", which every version contains, so it could never update one.)
    local SITECUSTOMIZE_VERSION="v4-ffmpeg-local"

    if [[ -f "$TARGET" ]] && grep -q "sitecustomize $SITECUSTOMIZE_VERSION" "$TARGET" 2>/dev/null; then
        echo "[sitecustomize] Already configured ($SITECUSTOMIZE_VERSION)."
        return
    fi
    echo "[sitecustomize] Writing conda library preloader ($SITECUSTOMIZE_VERSION) → $TARGET"
    cat > "$TARGET" << 'PYEOF'
"""Preload conda's own copies of libraries that clash with the system's.

Auto-generated by setup_env.sh — sitecustomize v4-ffmpeg-local. Do not edit by hand;
change write_sitecustomize() in setup_env.sh and re-run the installer.

Both entries below fix the same shape of bug: a C extension resolves a SONAME to
the system's copy of a library while the rest of the process is using conda's,
and the two disagree. Loading conda's first, RTLD_GLOBAL, makes the conda copy
win for everything that comes later.

1. libstdc++ — extensions compiled with GCC 14+ need CXXABI_1.3.15, which the
   system libstdc++ may be too old to provide.

2. FFmpeg 8 — torchcodec tries FFmpeg 8, 7, 6, 5, 4 in turn and keeps the first
   that fully loads. Without this preload it silently lands on the SYSTEM FFmpeg
   6, even though conda ships a complete FFmpeg 8 (libavutil 60 + libav{codec,
   format,device} 62): torchcodec's own FFmpeg-8 binaries cannot resolve conda's
   SONAMEs at dlopen time, and pyav's bundled FFmpeg 7 is auditwheel-renamed
   (libavutil-<hash>.so.59) so it never matches either.

   Falling back to the system FFmpeg 6 is fragile as well as unintended: that
   chain pulls in the system libncursesw, which — once anything has loaded
   conda's libtinfo — fails with "undefined symbol: _nc_safe_fopen". `import
   readline` is enough to trigger it, which is why the whole video test suite
   fails under pytest but passes in a plain interpreter. The error surfaces as
   "Could not load libtorchcodec ... FFmpeg is not properly installed", pointing
   nowhere near the actual cause.

   Preloading conda's set makes torchcodec select FFmpeg 8 and stay there.

   The FFmpeg entries MUST be RTLD_LOCAL. Loading them RTLD_GLOBAL fixes
   torchcodec but segfaults pyav: pyav carries its own auditwheel-renamed
   FFmpeg 7, and with FFmpeg 8's av_* symbols in the global scope pyav's calls
   bind across ABI versions. Encoding then crashes (test_streaming_video_encoder,
   test_datasets, test_aggregate, test_dataset_tools all core-dumped) — a strictly
   worse trade, since encoding is what recording depends on. RTLD_LOCAL still
   satisfies torchcodec's dlopen, because the loader resolves a dependency
   against any already-loaded object with a matching SONAME regardless of mode;
   it just keeps conda's symbols out of the global namespace. Verified: with
   RTLD_LOCAL, torchcodec reports FFmpeg 8 while pyav still reports libavutil 59.

Why not LD_LIBRARY_PATH instead of preloading at all: setup_env.sh grants the
interpreter cap_sys_nice (see grant_rt_scheduling, needed for the RT control
threads). A binary with file capabilities runs in secure-execution mode, where
the dynamic linker ignores LD_LIBRARY_PATH entirely. Preloading is what is left.
"""
import ctypes
import os
import sys

# (filename, dlopen mode) — see the module docstring for why the modes differ.
_PRELOAD = (
    ("libstdc++.so.6", ctypes.RTLD_GLOBAL),
    # FFmpeg 8, in dependency order. LOCAL on purpose — GLOBAL breaks pyav.
    ("libavutil.so.60", ctypes.RTLD_LOCAL),
    ("libavcodec.so.62", ctypes.RTLD_LOCAL),
    ("libavformat.so.62", ctypes.RTLD_LOCAL),
    ("libavdevice.so.62", ctypes.RTLD_LOCAL),
)

# sys.prefix, not $CONDA_PREFIX: this file lives in the environment it describes,
# and sys.prefix is right whether or not the environment was activated. Keying off
# the environment variable meant every un-activated invocation — an absolute path
# to bin/python, a systemd unit, cron — silently skipped the preloads and got the
# system libraries instead.
for _name, _mode in _PRELOAD:
    _path = os.path.join(sys.prefix, "lib", _name)
    if os.path.exists(_path):
        try:
            ctypes.CDLL(_path, mode=_mode)
        except Exception:
            # Best effort: a missing or unloadable library just means the previous
            # behaviour, never a hard failure at interpreter start.
            pass
PYEOF
}

# Flexiv RDK (and the ARX5 SDK) spawn SCHED_FIFO real-time control threads. Raising
# a thread to real-time priority requires CAP_SYS_NICE; a normal user lacks it, so
# the RDK Scheduler logs "Failed to set thread priority: root privilege is required"
# and silently downgrades the 1 kHz control loop to normal scheduling (jittery, unsafe
# on real hardware). Grant the capability to the *resolved* interpreter binary (setcap
# follows the conda bin/python symlink and writes the real file). Idempotent; harmless
# for non-robot scripts since cap_sys_nice only permits raising scheduling priority.
grant_rt_scheduling() {
    local PY_REAL
    PY_REAL="$(readlink -f "${CONDA_PREFIX}/bin/python")"
    if ! command -v setcap >/dev/null 2>&1; then
        echo "[rt-sched] WARN: 'setcap' not found — install it with 'sudo apt install libcap2-bin'."
        echo "[rt-sched]       Real-time thread priority will be unavailable until then."
        return 0
    fi
    echo "[rt-sched] Granting cap_sys_nice to $PY_REAL (needs sudo)..."
    if sudo setcap cap_sys_nice=ep "$PY_REAL"; then
        echo "[rt-sched] Done. Verify with: getcap $PY_REAL"
    else
        echo "[rt-sched] WARN: setcap failed — RT control threads will run at normal priority."
    fi
}

# conda installs a udev/ directory that confuses ctypes.util.find_library("udev"),
# causing pyudev/xensesdk to crash with "OSError: .../lib/udev: Is a directory".
fix_udev_discovery() {
    if [[ -d "${CONDA_PREFIX}/lib/udev" ]]; then
        echo "[udev] Renaming ${CONDA_PREFIX}/lib/udev to avoid pyudev clash..."
        local target="${CONDA_PREFIX}/lib/udev.rules.d"
        [[ -e "$target" ]] && target="${target}.bak.$(date +%s)"
        mv "${CONDA_PREFIX}/lib/udev" "$target" || true
    fi
    if [[ -e "${CONDA_PREFIX}/lib/libudev.so.1" && ! -e "${CONDA_PREFIX}/lib/libudev.so" ]]; then
        ln -s libudev.so.1 "${CONDA_PREFIX}/lib/libudev.so" || true
    fi
}

# TorchCodec follows an explicit compatibility matrix with PyTorch rather than
# a generic semver rule. Keep the expected version here so setup_env.sh can
# validate the installed wheel against the active torch release.
expected_torchcodec_version() {
    case "$1" in
        2.10) echo "0.10.0" ;;
        2.9) echo "0.9.1" ;;
        2.8) echo "0.7.0" ;;
        2.7) echo "0.5" ;;
        2.6) echo "0.2.1" ;;
        2.5) echo "0.1.1" ;;
        2.4) echo "0.0.3" ;;
        *) echo "" ;;
    esac
}

get_torch_major_minor() {
    python - <<'PY'
import re

try:
    import torch
except Exception:
    print("")
    raise SystemExit(0)

match = re.match(r"^(\d+)\.(\d+)", torch.__version__)
print(".".join(match.groups()) if match else "")
PY
}

version_matches_expected_release() {
    python - "$1" "$2" <<'PY'
import sys

from packaging.version import Version

actual, expected = sys.argv[1], sys.argv[2]

try:
    actual_release = Version(actual.split("+", 1)[0]).release
    expected_release = Version(expected).release
except Exception:
    print("no")
    raise SystemExit(0)

print("yes" if actual_release == expected_release else "no")
PY
}

# Installs or upgrades ONE package to >=min_version. `--upgrade-package`, not
# `--upgrade`: uv's `--upgrade` drops the prefer-installed rule for the whole
# resolution, so it also walks every dependency up to the newest release --
# which is how conda-owned packages get overwritten (check_conda_uv_consistency).
ensure_python_package_min_version() {
    local package_name=$1
    local min_version=$2

    local current_version
    current_version="$(python - "$package_name" <<'PY'
import sys
from importlib.metadata import PackageNotFoundError, version

package_name = sys.argv[1]

try:
    print(version(package_name))
except PackageNotFoundError:
    print("")
PY
)"

    if [[ -z "$current_version" ]]; then
        echo "[python] Installing missing package: $package_name>=$min_version"
        uv pip install --upgrade-package "$package_name" "$package_name>=$min_version"
        return
    fi

    local is_compatible
    is_compatible="$(python - "$current_version" "$min_version" <<'PY'
import sys

from packaging.version import Version

current_version, min_version = sys.argv[1], sys.argv[2]
print("yes" if Version(current_version) >= Version(min_version) else "no")
PY
)"

    if [[ "$is_compatible" == "yes" ]]; then
        echo "[python] Keeping $package_name==$current_version"
    else
        echo "[python] Upgrading $package_name from $current_version to >=$min_version"
        uv pip install --upgrade-package "$package_name" "$package_name>=$min_version"
    fi
}

# Report packages that conda and uv both own at different versions.
#
# conda tracks its files in conda-meta/<pkg>.json; uv/pip track theirs in
# <pkg>.dist-info/RECORD, and neither reads the other's ledger. uv CAN see
# conda's dist-info, so `uv pip install` over a conda package uninstalls it
# cleanly on the pip side -- but conda-meta still claims ownership. conda
# cannot see RECORD at all, so the next `mamba env update` relinks conda's
# copy over uv's and leaves every file uv added that conda's list omits.
# When the two versions moved a module into a package (pip's build_env.py ->
# build_env/, numpy's ctypeslib.py -> ctypeslib/) the leftover package
# shadows the module and the import dies.
#
# Only flags packages whose file sets actually overlap: conda's C++ spdlog
# (include/, lib/) and the PyPI spdlog Python binding (site-packages/) share
# a name but no files, and that is fine.
check_conda_uv_consistency() {
    python - "$CONDA_PREFIX" <<'PYEOF'
import csv, glob, json, os, re, sys

prefix = sys.argv[1]
sp = f"lib/python{sys.version_info.major}.{sys.version_info.minor}/site-packages/"

def conda_pkgs():
    for meta in glob.glob(os.path.join(prefix, "conda-meta", "*.json")):
        try:
            d = json.load(open(meta))
        except Exception:
            continue
        if d.get("name"):
            yield d["name"], d.get("version"), {
                f for f in d.get("files", []) if not f.endswith(".pyc")
            }

def dist_infos(name):
    pats = {name, name.replace("-", "_"), name.replace("_", "-")}
    seen = {}
    for pat in pats:
        for di in glob.glob(os.path.join(prefix, sp + pat + "-*.dist-info")):
            m = re.match(r".*-([^-]+)\.dist-info$", os.path.basename(di))
            rec = os.path.join(di, "RECORD")
            if not m or not os.path.exists(rec):
                continue
            files = set()
            with open(rec, newline="") as fh:
                for row in csv.reader(fh):
                    if row and row[0] and not row[0].endswith(".pyc"):
                        files.add(os.path.normpath(os.path.join(sp, row[0])))
            seen[m.group(1)] = (di, files)
    return seen

bad = []
for name, cver, cfiles in conda_pkgs():
    for uver, (di, ufiles) in dist_infos(name).items():
        if uver == cver or not (cfiles & ufiles):
            continue
        missing = sum(1 for f in cfiles if not os.path.exists(os.path.join(prefix, f)))
        di_rel = os.path.relpath(di, prefix)
        extra = sorted(f for f in ufiles - cfiles if not f.startswith(di_rel))
        bad.append((name, cver, uver, len(cfiles & ufiles), missing, len(cfiles), di, extra))

# The per-user site directory (~/.local/lib/pythonX.Y/site-packages) is not part
# of this env but conda envs inherit it, so a `pip install --user` anywhere on the
# host can shadow env packages. setup_env.sh sets PYTHONNOUSERSITE=1 to keep it off
# sys.path; this catches the case where that has been lost or overridden.
import site

shadow = []
usersite = site.getusersitepackages()
if site.ENABLE_USER_SITE and usersite in sys.path and os.path.isdir(usersite):
    def scan(d):
        found = {}
        for pat in ("*.dist-info", "*.egg-info"):
            for path in glob.glob(os.path.join(d, pat)):
                m = re.match(r"(.+)-([^-]+)\.(?:dist|egg)-info$", os.path.basename(path))
                if m:
                    found[m.group(1).lower().replace("_", "-")] = m.group(2)
        return found
    env_pkgs, user_pkgs = scan(os.path.join(prefix, sp)), scan(usersite)
    for name, uver in sorted(user_pkgs.items()):
        ever = env_pkgs.get(name)
        if ever != uver:
            shadow.append((name, ever or "-- (only in ~/.local)", uver))

if not bad and not shadow:
    print("[OK]    conda/uv package ownership is consistent.")
    print("[OK]    ~/.local site-packages is not on sys.path.")
    sys.exit(0)

if shadow:
    print("[WARN]  ~/.local/lib site-packages is on sys.path and disagrees with the env.")
    print("[WARN]  Whichever sorts first on sys.path wins, which is not something to")
    print("[WARN]  rely on. Re-run setup_env.sh, or set PYTHONNOUSERSITE=1 by hand:")
    print("[WARN]    conda env config vars set PYTHONNOUSERSITE=1 -n $CONDA_DEFAULT_ENV")
    print(f"[WARN]  {'package':22s} {'in env':22s} {'in ~/.local'}")
    for name, ever, uver in shadow:
        print(f"[WARN]  {name:22s} {ever:22s} {uver}")
    if bad:
        print("[WARN]")

if not bad:
    sys.exit(0)

print("[WARN]  These packages are owned by BOTH conda and uv at different versions.")
print("[WARN]  The next `mamba env update` will relink conda's copy over uv's and")
print("[WARN]  leave uv's extra files behind, which is how pip broke with")
print("[WARN]  \"ImportError: cannot import name 'get_runnable_pip'\".")
print(f"[WARN]  {'package':22s} {'conda-meta':12s} {'on disk':12s} {'shared':>7s} {'conda files gone':>17s}")
for name, cver, uver, shared, missing, total, _, _ in sorted(bad):
    print(f"[WARN]  {name:22s} {cver:12s} {uver:12s} {shared:7d} {f'{missing}/{total}':>17s}")
print("[WARN]  Fix by making one side own each: pin it in conda_environment.yaml to")
print("[WARN]  the version the wheel stack needs, or stop uv from upgrading it")
print("[WARN]  (`uv pip install --upgrade` upgrades every dependency in the")
print("[WARN]  resolution, not just the named package; use --upgrade-package).")
print("[WARN]  To put this env back on conda's copy right now, per package:")
for name, cver, uver, _, _, _, di, extra in sorted(bad):
    print(f"[WARN]    mamba install -p {prefix} -y --force-reinstall '{name}=={cver}'")
    print(f"[WARN]    rm -rf '{di}'")
    if extra:
        paths = " ".join(f"'{os.path.join(prefix, f)}'" for f in extra[:4])
        more = f"  # +{len(extra) - 4} more, see its RECORD" if len(extra) > 4 else ""
        print(f"[WARN]    rm -f {paths}{more}")
PYEOF
}

# ── Hardware module: ARX5 ─────────────────────────────────────────────────────

install_arx5() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " ARX5 SDK  →  pyarx"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/ARX5_SDK"
    if [[ ! -d "$SDK_DIR" ]]; then
        echo "ERROR: $SDK_DIR not found."
        echo "  Run: git submodule update --init third_party/ARX5_SDK"
        return 1
    fi

    # The PyPI spdlog package installs conflicting C++ headers — remove it first.
    uv pip uninstall spdlog 2>/dev/null || true

    bash "$SDK_DIR/build_python.sh"

    write_sitecustomize
    echo "[arx5] Done. Verify with: python -c 'import pyarx; print(pyarx)'"
}

# ── Hardware module: Flexiv ───────────────────────────────────────────────────

install_flexiv() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " libpyflexiv  →  flexiv_rt"
    echo "══════════════════════════════════════════"

    local LIB_DIR="$PROJECT_ROOT/third_party/libpyflexiv"
    local RDK_INSTALL="${RDK_INSTALL_PATH:-$HOME/rdk_install}"

    if [[ ! -d "$LIB_DIR" ]]; then
        echo "ERROR: $LIB_DIR not found."
        echo "  Run: git submodule update --init third_party/libpyflexiv"
        return 1
    fi

    # The vendored RDK deps (tinyxml2 8.0.0, foonathan_memory, Fast-CDR,
    # Fast-DDS) are pinned to ancient releases whose CMakeLists declare
    # cmake_minimum_required() < 3.5 AND explicitly cmake_policy(SET CMP0063
    # OLD). CMake 4.x (shipped in our conda env) rejects BOTH: the min version
    # (recoverable via CMAKE_POLICY_VERSION_MINIMUM=3.5) AND — fatally —
    # cmake_policy(SET CMP0063 OLD), which errors with "Policy CMP0063 may not
    # be set to OLD behavior because this version of CMake no longer supports
    # it" and has NO override. So a real CMake < 4.0 is mandatory. The deps'
    # *installed* package configs can trip cmake 4.x at find_package() time too,
    # so the binding (Stage 2) is built with the same legacy cmake.
    local LEGACY_CMAKE=""
    for _c in /usr/bin/cmake cmake3; do
        _cpath="$(command -v "$_c" 2>/dev/null)" || continue
        if "$_cpath" --version | head -1 | grep -qE 'version [123]\.'; then
            LEGACY_CMAKE="$_cpath"
            break
        fi
    done
    if [[ -z "$LEGACY_CMAKE" ]]; then
        # No system CMake < 4.0. Kitware's apt repo now ships only 4.x, so
        # `apt-get install cmake` can't help. Provision cmake<4 (3.31.x) from
        # PyPI into an isolated uv venv — a self-contained binary, no sudo, and
        # it does NOT disturb the conda env's cmake 4.x. Cached across runs.
        # NB: use the wheel's bundled data/bin/cmake directly; the venv bin/cmake
        # console-script wrapper misresolves outside an activated venv.
        local CMAKE3_VENV="${XDG_CACHE_HOME:-$HOME/.cache}/lerobot-xense/cmake3-venv"
        LEGACY_CMAKE="$(compgen -G "$CMAKE3_VENV/lib/python*/site-packages/cmake/data/bin/cmake" 2>/dev/null | head -1 || true)"
        if [[ -z "$LEGACY_CMAKE" || ! -x "$LEGACY_CMAKE" ]]; then
            echo "[flexiv] No system CMake < 4.0 found — provisioning cmake<4 from PyPI"
            echo "[flexiv]   into $CMAKE3_VENV (one-time; tinyxml2/Fast-DDS need CMP0063 OLD)"
            uv venv --python 3.12 "$CMAKE3_VENV" >/dev/null \
                && uv pip install --quiet --python "$CMAKE3_VENV/bin/python" "cmake<4"
            LEGACY_CMAKE="$(compgen -G "$CMAKE3_VENV/lib/python*/site-packages/cmake/data/bin/cmake" 2>/dev/null | head -1 || true)"
        fi
        if [[ -z "$LEGACY_CMAKE" || ! -x "$LEGACY_CMAKE" ]] \
           || ! "$LEGACY_CMAKE" --version | head -1 | grep -qE 'version 3\.'; then
            echo "[flexiv] ERROR: could not provision a CMake < 4.0 to build flexiv_rt"
            echo "[flexiv]        (tinyxml2/Fast-DDS use CMP0063 OLD, removed in CMake 4)."
            echo "[flexiv]        Install one manually, e.g.:  uv tool install 'cmake<4'"
            return 1
        fi
    fi
    # Shim it ahead of conda's cmake 4.x on PATH. Bare `cmake` calls inside the
    # submodule build scripts and the pip build backend then resolve to it.
    local CMAKE_SHIM
    CMAKE_SHIM="$(mktemp -d)"
    ln -sf "$LEGACY_CMAKE" "$CMAKE_SHIM/cmake"
    echo "[flexiv] Using $("$LEGACY_CMAKE" --version | head -1) ($LEGACY_CMAKE) for all flexiv builds"

    # Stage 1: build ~/rdk_install (RDK static lib + its C++ deps).
    # Idempotent — skip if a previous run already populated it.
    if [[ ! -f "$RDK_INSTALL/include/flexiv/rdk/robot.hpp" ]]; then
        echo "[flexiv] Building RDK + C++ dependencies into $RDK_INSTALL"
        echo "[flexiv] (one-time, ~10-30 min: eigen, spdlog, tinyxml2, foonathan_memory, Fast-CDR, Fast-DDS)"

        # flexiv_rdk is a nested submodule of libpyflexiv; ensure it is present.
        if [[ ! -f "$LIB_DIR/flexiv_rdk/thirdparty/build_and_install_dependencies.sh" ]]; then
            echo "[flexiv] Initializing flexiv_rdk submodule..."
            git -C "$LIB_DIR" submodule update --init flexiv_rdk || {
                echo "[flexiv] ERROR: failed to init flexiv_rdk submodule."
                return 1
            }
        fi

        # Subshell so the PATH/policy overrides don't leak to other installers.
        (
            set -e
            export PATH="$CMAKE_SHIM:$PATH"
            export CMAKE_POLICY_VERSION_MINIMUM=3.5  # belt-and-braces for < 3.5 mins

            # Force Fast-DDS to use its OWN vendored asio, not the system one.
            # install_Fast-DDS.sh hardcodes -DTHIRDPARTY_Asio=ON, which means
            # "use the bundle only if asio isn't found elsewhere". If the host has
            # apt `libasio-dev` (present on some 22.04 boxes, absent on the 24.04
            # box this was first tested on), CMake's find_path resolves asio to
            # /usr/include and — because that's a system prefix — emits NO -I flag.
            # The conda cross-compiler only searches its own sysroot, never the
            # host /usr/include, so the fastrtps build then dies with
            # "fatal error: asio.hpp: No such file or directory".
            # find_path searches CMAKE_PREFIX_PATH (this env var included) BEFORE
            # the system dirs, so prepending Fast-DDS's bundled asio prefix makes
            # configure resolve there — a non-system path CMake passes with -I —
            # regardless of whether libasio-dev is installed. The path need not
            # exist yet: it is created by the submodule init inside the build
            # script and only read at Fast-DDS configure time. We can't fix this
            # in install_Fast-DDS.sh itself since thirdparty/ is vendored.
            export CMAKE_PREFIX_PATH="$LIB_DIR/flexiv_rdk/thirdparty/cloned/Fast-DDS/thirdparty/asio/asio${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}"

            cd "$LIB_DIR/flexiv_rdk/thirdparty"
            bash build_and_install_dependencies.sh "$RDK_INSTALL" "$(nproc)"

            # Install flexiv_rdk itself (headers + prebuilt static lib) into RDK_INSTALL.
            cd "$LIB_DIR/flexiv_rdk"
            rm -rf build && mkdir -p build && cd build
            cmake .. \
                -DCMAKE_INSTALL_PREFIX="$RDK_INSTALL" \
                -DCMAKE_PREFIX_PATH="$RDK_INSTALL"
            cmake --build . --target install --config Release -j"$(nproc)"
        ) || {
            echo "[flexiv] ERROR: RDK dependency build failed (see output above)."
            return 1
        }
        echo "[flexiv] RDK install complete: $RDK_INSTALL"
    else
        echo "[flexiv] Reusing existing RDK install: $RDK_INSTALL"
    fi

    # Stage 2: build Python bindings (inside conda env, with the legacy cmake)
    # IMPORTANT: only pass ~/rdk_install as CMAKE_PREFIX_PATH.
    # Do NOT include $CONDA_PREFIX — conda contains a different spdlog version
    # that will cause header conflicts (see third_party/libpyflexiv/README.md).
    local BUILD_DIR="$LIB_DIR/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    # Pin tinyxml2 to the STATIC build inside ~/rdk_install. The conda env also
    # ships tinyxml2 (11.x, pulled in by urdfdom / ros-humble-tinyxml2-vendor)
    # with a tinyxml2-config.cmake exposing a SHARED target. fastrtps-config.cmake
    # does find_package(TinyXML2) — and CMake only matches that against filenames
    # `TinyXML2Config.cmake` or `tinyxml2-config.cmake`. The RDK deps install the
    # config as `tinyxml2Config.cmake` (lowercase + capital C), which does NOT
    # match, so find_package(TinyXML2) silently picks up conda's shared 11.x.
    # The binding then calls Fast-DDS (compiled against tinyxml2 8.0.0) through a
    # different-ABI tinyxml2 at runtime → segfault in
    # XMLProfileManager::loadDefaultXMLFile() the instant a Robot is created.
    #
    # Fix: drop a matching-named alias next to the static config so
    # find_package(TinyXML2) resolves to 8.0.0, and pin TinyXML2_DIR to it
    # (note the exact PascalCase — the hint var must match the find_package name).
    local TX2_CMAKE_DIR="$RDK_INSTALL/lib/cmake/tinyxml2"
    if [[ -f "$TX2_CMAKE_DIR/tinyxml2Config.cmake" ]]; then
        ln -sf tinyxml2Config.cmake "$TX2_CMAKE_DIR/tinyxml2-config.cmake"
        [[ -f "$TX2_CMAKE_DIR/tinyxml2ConfigVersion.cmake" ]] && \
            ln -sf tinyxml2ConfigVersion.cmake "$TX2_CMAKE_DIR/tinyxml2-config-version.cmake"
    fi

    "$LEGACY_CMAKE" \
        -S "$LIB_DIR" \
        -B "$BUILD_DIR" \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="$RDK_INSTALL" \
        -DTinyXML2_DIR="$TX2_CMAKE_DIR" \
        -DPython3_EXECUTABLE="$(which python)"

    "$LEGACY_CMAKE" --build "$BUILD_DIR" -j"$(nproc)"

    # The editable install re-runs the build backend, which calls bare `cmake`;
    # the shim on PATH keeps it on the legacy cmake too.
    PATH="$CMAKE_SHIM:$PATH" uv pip install -e "$LIB_DIR" --no-build-isolation

    write_sitecustomize
    grant_rt_scheduling
    echo "[flexiv] RT SDK done. Verify with: python -c 'import flexiv_rt; print(flexiv_rt)'"

    # Install Flexiv NRT Python SDK from PyPI
    echo ""
    echo "[flexiv] Installing NRT SDK (flexivrdk)..."
    uv pip install "flexivrdk==1.8.0"
    echo "[flexiv] NRT SDK done. Verify with: python -c 'import flexivrdk; print(flexivrdk)'"
}

# ── Hardware module: Pico4 ────────────────────────────────────────────────────

# Install the XenseVR PC Service daemon from its .deb. The package (~116 MB) is
# the binary service the Pico4 teleop/tracker talks to (installs to
# /opt/apps/roboticsservice); it is NOT vendored in-repo. By default,
# setup_env.sh downloads the matching-arch asset directly from the GitHub release
# ($XENSEVR_DEB_URL overrides the default release URL).
# $XENSEVR_DEB remains an explicit path override for offline/patched builds; no
# implicit dist/ or ~/Downloads cache lookup is done.
# Non-fatal on download failure: install_pico4() checks for the SDK afterwards
# and reports the real problem there. Idempotent: same installed version is skipped.
install_xensevr_service() {
    echo ""
    echo "── XenseVR PC Service (.deb daemon) ──"

    local ARCH DEB_VER DEB_URL DEB
    ARCH="$(dpkg --print-architecture 2>/dev/null || echo amd64)"   # amd64 | arm64
    DEB_VER="0.2.1"

    # 0.2.x ships amd64 only. Without this, an arm64 host would build a URL
    # for an asset that does not exist and fail with a bare 404 — pinning it
    # to the last release that has an arm64 build is both truthful and
    # working, at the cost of no Pico camera support there.
    if [[ "$ARCH" == "arm64" && -z "${XENSEVR_DEB_URL:-}${XENSEVR_DEB:-}" ]]; then
        DEB_VER="0.1.0"
        echo "  NOTE: arm64 detected — pinning to v${DEB_VER}, the newest release with"
        echo "        an arm64 asset. 0.2.x (Pico camera support) is amd64-only, and"
        echo "        XenseVR-PC-Service dropped its aarch64 tree, so building one is"
        echo "        no longer a matter of running a script in that repository."
    fi

    DEB_URL="${XENSEVR_DEB_URL:-https://github.com/XenseRobotics-AI/XenseVR-PC-Service/releases/download/v${DEB_VER}/XenseVR-PC-Service_${DEB_VER}_${ARCH}.deb}"

    local WANT INSTALLED STATUS
    # Check the status, not just the version. `dpkg -r` leaves the package in
    # `deinstall ok config-files`, and dpkg-query still reports its version
    # there — so matching on the version alone declares a daemon installed
    # when /opt/apps/roboticsservice is gone, skips the install, and fails
    # later somewhere far less obvious.
    STATUS="$(dpkg-query -W -f='${Status}' xensevr-pc-service 2>/dev/null || true)"
    INSTALLED="$(dpkg-query -W -f='${Version}' xensevr-pc-service 2>/dev/null || true)"

    # Decide before downloading. DEB_VER already names the version this script
    # would install, so fetching 116 MB only to read the same number back out of
    # the package is waste on every re-run of --install. An explicit override is
    # exempt: it can be a different build carrying the same version, and only
    # the file itself can say.
    if [[ -z "${XENSEVR_DEB:-}${XENSEVR_DEB_URL:-}" && "$STATUS" == "install ok installed" && "$INSTALLED" == "$DEB_VER" ]]; then
        echo "  xensevr-pc-service $INSTALLED already installed — skipping."
        return 0
    fi

    DEB="${XENSEVR_DEB:-}"
    if [[ -n "$DEB" ]]; then
        if [[ ! -f "$DEB" ]]; then
            echo "  WARN: XENSEVR_DEB points to a missing file: $DEB"
            echo "  WARN: skipping service install."
            return 0
        fi
        echo "  Using explicit .deb override: $DEB"
    else
        DEB="${TMPDIR:-/tmp}/XenseVR-PC-Service_${DEB_VER}_${ARCH}.deb"
        if [[ -f "$DEB" ]] && dpkg-deb -f "$DEB" Version >/dev/null 2>&1; then
            echo "  Reusing previously downloaded $DEB"
        else
            # An unreadable leftover is worth less than the bandwidth to replace it.
            rm -f "$DEB"
            echo "  Downloading ${ARCH} asset from:"
            echo "    $DEB_URL"
            # ~116 MB. Retry and resume rather than losing the whole transfer to
            # one dropped connection — this package is now the only source of the
            # client SDK the Python bindings link against, so a failure here is
            # not something a local build can paper over.
            #
            # Staged through .part deliberately: handing a *complete* file to
            # `curl -C -` asks for a range that starts at EOF, the server answers
            # 416, and --retry-all-errors then retries that five times before
            # giving up. Only a partial transfer is ever resumed.
            local RETRY=(--retry 5 --retry-delay 2)
            if curl --help all 2>/dev/null | grep -q -- '--retry-all-errors'; then
                RETRY+=(--retry-all-errors)   # curl >= 7.71; covers a mid-transfer drop
            fi
            if ! curl -fL "${RETRY[@]}" -C - "$DEB_URL" -o "$DEB.part"; then
                echo "  WARN: download failed — skipping service install."
                echo "  The partial file is kept at $DEB.part — re-run to resume it."
                echo "  Or get it from https://github.com/XenseRobotics-AI/XenseVR-PC-Service/releases"
                echo "  then: sudo dpkg -i XenseVR-PC-Service_*_${ARCH}.deb"
                return 0
            fi
            mv "$DEB.part" "$DEB"
        fi
    fi

    WANT="$(dpkg-deb -f "$DEB" Version 2>/dev/null)"
    if [[ "$STATUS" == "install ok installed" && "$INSTALLED" == "$WANT" ]]; then
        echo "  xensevr-pc-service $INSTALLED already installed — skipping."
        return 0
    fi

    echo "  Installing xensevr-pc-service ${WANT:-?} from: $DEB"
    sudo dpkg -i "$DEB" || sudo apt-get install -f -y
    echo "  Installed to /opt/apps/roboticsservice. Start the service with:"
    echo "    /opt/apps/roboticsservice/runService.sh"
}

install_pico4() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " XenseVR-PC-Service  →  xensevr_pc_service_sdk"
    echo "══════════════════════════════════════════"

    local PYBIND_DIR="$PROJECT_ROOT/src/lerobot/teleoperators/pico4/xensevr-pc-service-pybind"

    # Install the PC Service daemon (.deb) the Python SDK will talk to. It also
    # ships the client SDK the bindings link against, which is why there is no
    # longer a XenseVR-PC-Service submodule to compile: the .deb's
    # libPXREARobotSDK.so is the same artifact that build used to produce, and
    # keeping a 33 MiB shallow checkout of prebuilt gRPC archives around to
    # rebuild it cost more than it was worth. The trade is that an SDK source
    # fix now has to travel through a .deb release rather than through
    # `--install`.
    install_xensevr_service

    # Take the header and .so straight out of the installed package. SDK/x64 on
    # amd64, SDK/arm64 on arm64 — the names come from the service's own install
    # step, not from dpkg's architecture strings.
    local SDK_ROOT="/opt/apps/roboticsservice/SDK"
    local SDK_LIBDIR
    case "$(dpkg --print-architecture 2>/dev/null || echo amd64)" in
        arm64) SDK_LIBDIR="$SDK_ROOT/arm64" ;;
        *)     SDK_LIBDIR="$SDK_ROOT/x64" ;;
    esac

    if [[ ! -f "$SDK_ROOT/include/PXREARobotSDK.h" || ! -f "$SDK_LIBDIR/libPXREARobotSDK.so" ]]; then
        echo "ERROR: the XenseVR PC Service SDK is not on this host."
        echo "  Expected:"
        echo "    $SDK_ROOT/include/PXREARobotSDK.h"
        echo "    $SDK_LIBDIR/libPXREARobotSDK.so"
        echo "  Both come from the xensevr-pc-service .deb, which the step above"
        echo "  installs. If that step warned about a failed download, fix that"
        echo "  first — the bindings cannot be built without it."
        return 1
    fi

    # Both architectures stage flat into include/ and lib/; the pybind
    # CMakeLists looks there on every UNIX host. nlohmann is not in the .deb —
    # it comes from conda (nlohmann_json in conda_environment.yaml) and the
    # CMakeLists find_package()s it.
    mkdir -p "$PYBIND_DIR/include" "$PYBIND_DIR/lib"
    cp "$SDK_ROOT/include/PXREARobotSDK.h" "$PYBIND_DIR/include/"
    cp "$SDK_LIBDIR/libPXREARobotSDK.so" "$PYBIND_DIR/lib/"

    # Build and install the Python bindings
    pushd "$PYBIND_DIR" > /dev/null
    rm -rf build *.egg-info
    uv pip uninstall xensevr_pc_service_sdk 2>/dev/null || true
    uv pip install . --no-build-isolation
    popd > /dev/null

    echo "[pico4] Done. Verify with: python -c 'import xensevr_pc_service_sdk; print(xensevr_pc_service_sdk)'"
}

# ── Hardware module: Xense ────────────────────────────────────────────────────

install_xense() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " xensesdk (PyPI) + XGripper"
    echo "══════════════════════════════════════════"

    local XENSESDK_VERSION="2.1.2"
    local GRIPPER_DIR="$PROJECT_ROOT/third_party/XGripper"

    # Check for pyproject.toml, not just the directory: a registered-but-not-
    # checked-out submodule leaves an empty dir, which passes -d but makes the
    # editable install below fail with "does not appear to be a Python project".
    if [[ ! -f "$GRIPPER_DIR/pyproject.toml" ]]; then
        echo "ERROR: $GRIPPER_DIR is missing or not initialized (no pyproject.toml)."
        echo "  Run: git submodule update --init third_party/XGripper"
        return 1
    fi

    fix_udev_discovery

    # Install xensesdk runtime deps explicitly because xensesdk is installed
    # with --no-deps below (keeps the shared ARX5/Robostack env's numpy/opencv/
    # cryptography pins from being disturbed by the wheel's own constraints —
    # notably xensesdk pins cryptography==43.0.3, which would DOWNGRADE the env's
    # 49.x otherwise). cypack/ormsgpack/cyclonedds-nightly are mandatory runtime
    # deps — cypack is the FIRST import in xensesdk/__init__.py and
    # ormsgpack/cyclonedds are needed by the ezros layer — so they must be
    # listed here or `import xensesdk` fails with ModuleNotFoundError.
    uv pip install \
        "numpy>=1.26.4,<2.3.0" \
        "opencv-python>=4.10" \
        "pillow>=12.0" \
        "cryptography>=46.0" \
        "PyYAML>=6.0" \
        "h5py>=3.10" \
        "scipy>=1.14" \
        "lz4>=4.0" \
        "psutil>=7.0" \
        "spdlog>=2.0" \
        "cypack>=0.1.2" \
        "ormsgpack>=1.11.0" \
        "cyclonedds-nightly==2025.7.29" \
        "pyudev; platform_system=='Linux'"
    # Install xensesdk from PyPI (pinned). The published cp312 manylinux wheel
    # carries the same patched libxense_c flash reader (concurrent-connect EBADF
    # fix) that was previously vendored under dist/: 2.0.1 ships a byte-identical
    # libxense_c.so.20 and a newer libxense_c.so.1.0.0 (the file the backend now
    # loads), so no separate xense_xu / pyxensexu build is needed. --no-deps keeps
    # the env's numpy/cryptography pins (see block above).
    uv pip install --no-deps --upgrade-package xensesdk "xensesdk==${XENSESDK_VERSION}"
    # Install XGripper from local submodule (import package: xgripper). It is
    # used by the serial / xense grippers and imports the xensesdk installed
    # above; --no-deps avoids PyPI wheels that are incomplete for Python 3.12.
    # Pure Python since the vendored libsurvive was retired — no compiler, no
    # CMake, no hidapi, and no LIBRARY_PATH smuggled past the build isolation.
    uv pip install -e "$GRIPPER_DIR" --no-deps
    # xensesdk requires a specific av version
    uv pip install av==15.1.0

    local PY_VER
    PY_VER="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

    # onnxruntime-gpu uses dlopen() and ignores LD_LIBRARY_PATH — patch its RPATH.
    local ONNX_SO="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so"
    if [[ -f "$ONNX_SO" ]]; then
        echo "[xense] Fixing onnxruntime-gpu RPATH..."
        uv pip install patchelf
        patchelf --set-rpath "${CONDA_PREFIX}/lib" "$ONNX_SO"
        echo "[xense] RPATH set: $(patchelf --print-rpath "$ONNX_SO")"
    fi

    # OpenCV's bundled Qt plugin causes XCB errors inside conda envs.
    local QXCB="${CONDA_PREFIX}/lib/python${PY_VER}/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
    if [[ -f "$QXCB" ]]; then
        echo "[xense] Removing OpenCV bundled Qt plugin: $QXCB"
        rm -f "$QXCB"
    fi

    if python - <<'PY'
from xensesdk.flash.linux_backend import LinuxFlashBackend
raise SystemExit(0 if LinuxFlashBackend().available else 1)
PY
    then
        echo "[xense] xensesdk flash backend (libxense_c) is available."
    else
        echo "[xense] ERROR: xensesdk flash backend verification failed."
        return 1
    fi

    echo "[xense] Done. Verify with: python -c 'import xensesdk; print(xensesdk)'"
}

# ── Hardware module: TacCap gripper SDK (xense.taccap) ───────────────────────

install_taccap() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " TacCap-Gripper SDK  →  xense.taccap"
    echo "══════════════════════════════════════════"

    local SDK_DIR="$PROJECT_ROOT/third_party/taccap-gripper"
    if [[ ! -f "$SDK_DIR/pyproject.toml" ]]; then
        echo "ERROR: $SDK_DIR not found (submodule not initialized)."
        echo "  Run: git submodule update --init --recursive third_party/taccap-gripper"
        return 1
    fi
    # Nested libxensesdk (lite C++ vision dep) must be present for the cmake build.
    if [[ ! -f "$SDK_DIR/third_party/libxensesdk/CMakeLists.txt" ]]; then
        echo "[taccap] Initializing nested libxensesdk submodule..."
        git -C "$SDK_DIR" submodule update --init --recursive || {
            echo "[taccap] ERROR: failed to init libxensesdk submodule."
            return 1
        }
    fi

    # Tactile path uses libxense/pyudev, same find_library("udev") pitfall as xensesdk.
    fix_udev_discovery

    # taccap's libxense-lite C++ build needs the OpenCV C++ headers and
    # nlohmann_json, which the lerobot env does NOT ship (it carries only the
    # cv2 wheel, not libopencv C++). These are now declared in
    # conda_environment.yaml so the env-create solves them together with the
    # robostack ROS stack (one coherent solve) — this fallback normally no-ops
    # because the guard below finds the headers already present.
    # eigen/openssl/cmake/ninja/gcc14 are already present. libopencv is the C++
    # runtime only — it does not disturb the pip-installed opencv-python.
    # Note: the env carries `libzlib` (runtime) but not `zlib` (dev) — the latter
    # provides the linkable libz.so symlink that libxensesdk's find_package(ZLIB)
    # needs (CMakeLists.txt:321). Trigger on a missing libz.so too.
    if [[ ! -f "${CONDA_PREFIX}/include/nlohmann/json.hpp" ]] || \
       ! compgen -G "${CONDA_PREFIX}/include/opencv4/opencv2/opencv.hpp" > /dev/null 2>&1 || \
       [[ ! -e "${CONDA_PREFIX}/lib/libz.so" ]]; then
        echo "[taccap] Installing C++ build deps (libopencv, nlohmann_json, zlib, pkg-config, make)..."
        # Include robostack-staging and DO NOT pin libopencv=4.12: a bare
        # conda-forge solve with that pin pulls libprotobuf 6.31 and evicts the
        # robostack ROS stack (ros-humble-kdl-parser → breaks pyarx). 4.13 links
        # libprotobuf 6.33.5 and coexists with ros2-distro-mutex.
        ${CONDA_CMD:-mamba} install -c robostack-staging -c conda-forge -y \
            "libopencv>=4.13" "nlohmann_json=3.11.3" "zlib=1.3.1" pkg-config make
    fi

    # --no-build-isolation (used below to keep the build on the env's cmake/ninja
    # instead of a freshly fetched PyPI one) requires the PEP 517 backend and
    # pybind11 to be present in-env — pre-install them.
    uv pip install "scikit-build-core>=0.10" "pybind11>=2.12"

    # scikit-build-core + pybind11 build. LIBRARY_PATH gives the conda cross-
    # compiler the conda libdir (same reason as XGripper). --no-deps keeps the
    # shared env's numpy/opencv pins; --no-build-isolation uses the env's
    # cmake/ninja instead of a freshly fetched PyPI one.
    LIBRARY_PATH="${CONDA_PREFIX}/lib${LIBRARY_PATH:+:$LIBRARY_PATH}" \
        uv pip install -e "$SDK_DIR" --no-deps --no-build-isolation

    echo "[taccap] Done. Verify with: python -c 'import xense.taccap; print(xense.taccap.__file__)'"
}

# ── Hardware module: Elite CS (bi_elite_cs66_rt / elite_cs66_rt) ─────────────

install_elite() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " Elite CS SDK (C++ + Python)  →  elite_cs_sdk"
    echo "══════════════════════════════════════════"

    local CPP_DIR="$PROJECT_ROOT/third_party/elite-robots-cs-sdk"
    local PY_DIR="$PROJECT_ROOT/third_party/elite-robots-cs-sdk-python"

    if [[ ! -f "$CPP_DIR/CMakeLists.txt" ]]; then
        echo "ERROR: $CPP_DIR not found."
        echo "  Run: git submodule update --init third_party/elite-robots-cs-sdk"
        return 1
    fi
    if [[ ! -f "$PY_DIR/CMakeLists.txt" ]]; then
        echo "ERROR: $PY_DIR not found."
        echo "  Run: git submodule update --init third_party/elite-robots-cs-sdk-python"
        return 1
    fi

    # C++ build prerequisites (system packages, see Elite BuildGuide):
    #   sudo apt install -y build-essential cmake libboost-all-dev libssh-dev \
    #                        libeigen3-dev liborocos-kdl-dev
    # Python build deps — the python_wheel target builds with --no-build-isolation.
    # Only the packages conda does NOT provide. pybind11, setuptools and wheel
    # all come from conda_environment.yaml; `uv pip install --upgrade` on them
    # overwrites conda's files in place, leaving conda-meta claiming a version
    # that is no longer on disk. The next `mamba env update` then relinks conda's
    # copy over uv's and leaves uv's extra files behind -- exactly how pip broke
    # with `ImportError: cannot import name 'get_runnable_pip'`.
    #
    # `--upgrade-package`, not `--upgrade`: uv's `--upgrade` drops the
    # prefer-installed rule for the WHOLE resolution, not just the named
    # packages. `--upgrade build` walked build's `packaging>=24.0` dependency
    # from conda's 26.2 to a 26.3 conda-forge does not ship (2026-09-01). `-P`
    # upgrades only the named packages and keeps every dependency where it is.
    uv pip install --upgrade-package pybind11-stubgen --upgrade-package build \
        pybind11-stubgen build

    # Build the pybind wheel, pointing the Python SDK at our LOCAL C++ SDK
    # submodule (ELITE_CS_SDK_REPO is required and must be a local path — the
    # Python build add_subdirectory()s it instead of fetching over the network).
    local BUILD_DIR="$PY_DIR/build"
    rm -rf "$BUILD_DIR"
    cmake -S "$PY_DIR" -B "$BUILD_DIR" \
        -DCMAKE_BUILD_TYPE=Release \
        -DELITE_CS_SDK_REPO="$CPP_DIR" \
        -DELITE_COMPILE_KIN_PLUGIN=ON \
        -DPython3_EXECUTABLE="$(which python)"
    cmake --build "$BUILD_DIR" --target python_wheel -j"$(nproc)"

    local WHEEL
    WHEEL="$(ls -t "$PY_DIR"/dist/elite_cs_sdk-*.whl 2>/dev/null | head -1)"
    if [[ -z "$WHEEL" ]]; then
        echo "[elite] ERROR: build did not produce a wheel under $PY_DIR/dist/"
        return 1
    fi
    uv pip install --force-reinstall "$WHEEL"

    echo "[elite] Done. Verify with: python -c 'import elite_cs_sdk; print(elite_cs_sdk.__file__)'"
}

# ── Hardware module: SpaceMouse ───────────────────────────────────────────────

install_spacemouse() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " SpaceMouse — pyspacemouse"
    echo "══════════════════════════════════════════"

    if ! compgen -G "${CONDA_PREFIX}/lib/libhidapi*.so*" > /dev/null; then
        echo "[spacemouse] WARN: hidapi shared library not found under ${CONDA_PREFIX}/lib"
        echo "[spacemouse] Re-run the conda environment update to install the conda-forge hidapi package."
        return 1
    fi

    uv pip install pyspacemouse
    echo "[spacemouse] No system-level udev or group changes were applied."
    echo "[spacemouse] If hidraw permissions are restricted on the host OS, configure them manually outside setup_env.sh."

    echo "[spacemouse] Done."
}

# ── Hardware module: Dynamixel (TRLC leader, SO arms, etc.) ─────────────────

install_dynamixel() {
    echo ""
    echo "══════════════════════════════════════════"
    echo " Dynamixel — dynamixel-sdk (Python)"
    echo "══════════════════════════════════════════"

    # Keep in sync with pyproject.toml: dynamixel = ["dynamixel-sdk>=3.7.31,<3.9.0"]
    if ! uv pip install "dynamixel-sdk>=3.7.31,<3.9.0"; then
        echo "[dynamixel] ERROR: pip install dynamixel-sdk failed"
        return 1
    fi
    echo "[dynamixel] Done. Verify with: python -c 'import dynamixel_sdk; print(dynamixel_sdk.__file__)'"
}

# Top-level usage. Hardware selectors are documented by `--install --help`.
print_general_usage() {
    cat <<'USAGE'
Usage: ./setup_env.sh <command> [options]
  --conda [env_name]     Create a conda environment (requires Miniconda/Anaconda)
  --mamba [env_name]     Create a mamba environment (requires Miniforge)
  --install [hardware]   Install base package + hardware SDK bindings.
                         No hardware selector => install ALL (backward compatible).
                         Run `./setup_env.sh --install --help` for the selector list.
  --help, -h             Show this message
USAGE
}

# ── Argument parsing ──────────────────────────────────────────────────────────

# Check if an environment name is provided
if [[ -n "$2" ]]; then
    ENV_NAME="$2"
else
    ENV_NAME="lerobot-xense"
fi

# Check if the --conda parameter is passed
if [[ "$1" == "--conda" ]]; then
    # Initialize conda
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    elif [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/anaconda3/etc/profile.d/conda.sh"
    else
        echo "Conda initialization script not found. Please install Miniconda3 or Anaconda3 or Miniforge3."
        exit 1
    fi
    create_environment "conda" "$ENV_NAME" || exit 1

# Check if the --mamba parameter is passed
elif [[ "$1" == "--mamba" ]]; then
    # Initialize mamba (miniforge)
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/conda.sh"
    elif [ -f "$HOME/mambaforge/etc/profile.d/conda.sh" ]; then
        . "$HOME/mambaforge/etc/profile.d/conda.sh"
    else
        echo "Mamba initialization script not found. Please install Miniforge3 or Mambaforge."
        exit 1
    fi
    # Also source mamba.sh if available for full mamba support
    if [ -f "$HOME/miniforge3/etc/profile.d/mamba.sh" ]; then
        . "$HOME/miniforge3/etc/profile.d/mamba.sh"
    elif [ -f "$HOME/mambaforge/etc/profile.d/mamba.sh" ]; then
        . "$HOME/mambaforge/etc/profile.d/mamba.sh"
    fi
    create_environment "mamba" "$ENV_NAME" || exit 1

# Check if the --install parameter is passed
elif [[ "$1" == "--install" ]]; then
    # ── Hardware selector parsing ─────────────────────────────────────────────
    # Per-hardware-family flags after --install restrict which SDK bindings get
    # built. No flags => install everything (backward compatible). Arm selectors
    # auto-include the xense gripper stack (the arms drive xense grippers).
    #   ./setup_env.sh --install                     # core + ALL hardware SDKs
    #   ./setup_env.sh --install --flexiv --taccap   # core + those (+ auto xense)
    #   ./setup_env.sh --install --core              # core only, no hardware SDK
    SELECTED=""
    add_key() { case " $SELECTED " in *" $1 "*) ;; *) SELECTED="$SELECTED $1" ;; esac; }
    is_sel()  { case " $SELECTED " in *" $1 "*) return 0 ;; *) return 1 ;; esac; }
    select_all_hw() { local k; for k in arx5 flexiv pico4 xense taccap elite spacemouse dynamixel; do add_key "$k"; done; }
    print_install_usage() {
        cat <<'USAGE'
Usage: ./setup_env.sh --install [hardware selectors]
  (no selector)         core + ALL hardware SDKs (default, backward compatible)
  --all                 core + ALL hardware SDKs (explicit)
  --core, --none        core only (no hardware SDK bindings)
Per-hardware-family selectors (arms auto-include the xense gripper stack):
  --flexiv,  --bi_flexiv     Flexiv Rizon4 RT    (+ xense)
  --elite,   --bi_elite      Elite CS66 RT       (+ xense)
  --taccap,  --bi_taccap     TacCap gripper      (+ xense)
  --xense                    Xense tactile sensors + XGripper serial gripper
  --arx5,    --bi_arx5       ARX5 arm
  --pico4,   --bi_pico4      Pico4 VR teleop
  --spacemouse               3D SpaceMouse teleop
  --dynamixel, --trlc        Dynamixel / TRLC leader teleop
Examples:
  ./setup_env.sh --install --flexiv --taccap
  ./setup_env.sh --install --core
USAGE
    }
    _hw_args=("${@:2}")
    if [[ ${#_hw_args[@]} -eq 0 ]]; then
        select_all_hw
    else
        for _a in "${_hw_args[@]}"; do
            case "$_a" in
                --all)                    select_all_hw ;;
                --core|--none)            : ;;  # no-op: core is always installed
                --flexiv|--bi_flexiv)     add_key flexiv; add_key xense ;;
                --elite|--bi_elite)       add_key elite;  add_key xense ;;
                --taccap|--bi_taccap)     add_key taccap; add_key xense ;;
                --xense)                  add_key xense ;;
                --arx5|--bi_arx5)         add_key arx5 ;;
                --pico4|--bi_pico4)       add_key pico4 ;;
                --spacemouse)             add_key spacemouse ;;
                --dynamixel|--trlc)       add_key dynamixel ;;
                --help|-h)                print_install_usage; exit 0 ;;
                *) echo "[ERROR] Unknown --install selector: $_a"; echo; print_install_usage; exit 1 ;;
            esac
        done
    fi
    SELECTED="$(echo "$SELECTED" | tr -s ' ' | sed 's/^ //; s/ $//')"
    if [[ -n "$SELECTED" ]]; then
        echo "[INFO] Selected hardware SDKs: $SELECTED"
    else
        echo "[INFO] Selected hardware SDKs: (core only — no hardware bindings)"
    fi

    # Get the currently activated conda environment name
    if [[ -z "${CONDA_DEFAULT_ENV}" ]]; then
        echo "Error: No conda/mamba environment is currently activated."
        echo "Please activate an environment first with: conda/mamba activate <env_name>"
        exit 1
    fi
    ENV_NAME=${CONDA_DEFAULT_ENV}

    # Detect conda/mamba command
    if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
        CONDA_CMD="mamba"
    else
        CONDA_CMD="conda"
    fi

    echo "[INFO] Updating conda environment '$ENV_NAME' from: $CONDA_ENV_FILE"
    if ! $CONDA_CMD env update -f "$CONDA_ENV_FILE" -n "$ENV_NAME"; then
        echo "[ERROR] Failed to update conda environment '$ENV_NAME' from: $CONDA_ENV_FILE"
        exit 1
    fi

    echo -e "\n[INFO] Conda dependencies installed/updated for '$ENV_NAME'.\n"

    # Keep ~/.local/lib/pythonX.Y/site-packages off this env's sys.path.
    #
    # conda envs inherit the per-user site directory, and this host has one:
    # a `pip install --user pillow-heif` on 2026-07-25 left 12 packages there,
    # six of which also exist in the env at different versions (pillow 12.3.0
    # vs 12.2.0, tqdm 4.68.4 vs 4.68.3, fsspec, huggingface-hub, filelock).
    # The env's site-packages currently sorts first so the env copy wins, but
    # that ordering is not something to rely on, and pillow-heif exists ONLY in
    # ~/.local -- so it is importable here despite not being a dependency of
    # this project. Deleting ~/.local is not an option: the system python3.12
    # shares it, and it belongs to the user, not to this repo.
    #
    # Exported as well as recorded, so the rest of THIS run also ignores it --
    # otherwise uv can see a ~/.local copy, consider the requirement satisfied,
    # and skip installing the package into the env.
    $CONDA_CMD env config vars set PYTHONNOUSERSITE=1 -n "$ENV_NAME" >/dev/null
    export PYTHONNOUSERSITE=1
    echo "[INFO] PYTHONNOUSERSITE=1 set for '$ENV_NAME' (ignores ~/.local site-packages)."
    # NOTE: do NOT upgrade pip here. `pip` is a conda dependency
    # (conda_environment.yaml), so conda owns those files. `uv pip install
    # --upgrade pip` writes a newer pip over them without conda knowing; the
    # next `conda env update` then relinks conda's older pip on top, leaving the
    # newer version's extra files behind (e.g. pip 26.2.1's `_internal/build_env/`
    # package shadowing 26.1.2's `_internal/build_env.py`). The result is a pip
    # that cannot import itself:
    #   ImportError: cannot import name 'get_runnable_pip' from 'pip._internal.utils.misc'
    # Nothing in this script calls `python -m pip` — every install below goes
    # through `uv pip` — so conda's pip is only there for the yaml `pip:` section.
    # If pip really must be upgraded, do it with conda/mamba, not uv.

    # Ensure editable installs (PEP 660) work without downgrading newer compatible packages.
    ensure_python_package_min_version setuptools 71.0.0
    ensure_python_package_min_version wheel 0.40.0

    # Workaround for Python ctypes.util.find_library("udev") on conda envs:
    # Hacking the udev library discovery to avoid issues with pyudev/xensesdk.
    # If $CONDA_PREFIX/lib/udev exists as a directory, Python may return that directory as the "udev" library,
    # causing pyudev/xensesdk to crash with: "OSError: .../lib/udev: Is a directory".
    fix_udev_discovery

    # evdev (pulled in by pynput) generates ecodes.c from /usr/include/linux/ at
    # build time, then compiles it with the conda cross-compiler which uses its
    # own sysroot. Ubuntu's linux-libc-dev now ships KEY_LINK_PHONE (added in
    # Linux 6.14), so evdev references it in ecodes.c, but the conda sysroot's
    # older kernel headers lack it.  Patch the sysroot header in place so the
    # conda compiler can find the constant without mixing incompatible glibc headers.
    _SYSROOT_CODES="${CONDA_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/include/linux/input-event-codes.h"
    if [[ -f "$_SYSROOT_CODES" ]] && ! grep -q "KEY_LINK_PHONE" "$_SYSROOT_CODES"; then
        echo "[INFO] Patching conda sysroot: adding KEY_LINK_PHONE to input-event-codes.h"
        printf '\n#ifndef KEY_LINK_PHONE\n#define KEY_LINK_PHONE 0x1bf  /* AL Phone Syncing, Linux 6.14 */\n#endif\n' >> "$_SYSROOT_CODES"
    fi

    echo "[INFO] Installing Lerobot from pyproject.toml"
    if uv pip install -e .; then
        echo "[INFO] Lerobot installed successfully!"
    else
        echo "[ERROR] Lerobot installation failed. See the error output above."
        exit 1
    fi

    # Verify critical package versions
    echo "[INFO] Verifying package versions..."
    TORCHCODEC_VER=$(python -c "import torchcodec; print(torchcodec.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    AV_VER=$(python -c "import av; print(av.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    TORCH_VER=$(python -c "import torch; print(torch.__version__)" 2>/dev/null || echo "NOT INSTALLED")
    TORCH_MAJOR_MINOR=$(get_torch_major_minor)
    EXPECTED_TORCHCODEC_VER=$(expected_torchcodec_version "$TORCH_MAJOR_MINOR")
    echo "  - torch: $TORCH_VER"
    if [[ -n "$EXPECTED_TORCHCODEC_VER" ]]; then
        echo "  - torchcodec: $TORCHCODEC_VER (should be $EXPECTED_TORCHCODEC_VER for torch $TORCH_MAJOR_MINOR)"
    else
        echo "  - torchcodec: $TORCHCODEC_VER (no compatibility override defined for torch $TORCH_VER)"
    fi
    echo "  - av (pyav): $AV_VER (should be 15.1.0)"

    if [[ -n "$EXPECTED_TORCHCODEC_VER" ]]; then
        if [[ "$(version_matches_expected_release "$TORCHCODEC_VER" "$EXPECTED_TORCHCODEC_VER")" != "yes" ]]; then
            echo "[WARN] torchcodec version mismatch! Expected $EXPECTED_TORCHCODEC_VER for torch $TORCH_MAJOR_MINOR, got $TORCHCODEC_VER"
            uv pip install "torchcodec==$EXPECTED_TORCHCODEC_VER" --force-reinstall
        fi
    else
        echo "[WARN] Skipping torchcodec pin verification for unsupported torch version: $TORCH_VER"
    fi

    if [[ "$AV_VER" != "15.1.0" ]]; then
        echo "[WARN] av (pyav) version mismatch! Expected 15.1.0, got $AV_VER"
        uv pip install av==15.1.0 --force-reinstall
    fi

    echo ""
    echo "[INFO] Installing hardware SDK bindings..."
    echo ""

    if is_sel arx5;       then install_arx5      || echo "[WARN] arx5 installation skipped or failed (see above)"; fi
    if is_sel flexiv;     then install_flexiv    || echo "[WARN] flexiv installation skipped or failed (see above)"; fi
    if is_sel pico4;      then ( install_pico4 ) || echo "[WARN] pico4 installation skipped or failed (see above)"; fi
    if is_sel xense;      then install_xense     || echo "[WARN] xense installation skipped or failed (see above)"; fi
    if is_sel taccap;     then install_taccap    || echo "[WARN] taccap installation skipped or failed (see above)"; fi
    if is_sel elite;      then install_elite     || echo "[WARN] elite installation skipped or failed (see above)"; fi
    if is_sel spacemouse; then install_spacemouse || echo "[WARN] spacemouse installation skipped or failed (see above)"; fi
    if is_sel dynamixel;  then install_dynamixel  || echo "[WARN] dynamixel-sdk installation skipped or failed (see above)"; fi


    # ── Post-install verification ────────────────────────────────────────────
    echo ""
    echo "══════════════════════════════════════════"
    echo " Post-install verification"
    echo "══════════════════════════════════════════"
    # Verify only the SDKs that were selected for install (lerobot core always).
    # spacemouse has no verify probe today — kept that way.
    _VERIFY_LINES='lerobot|import importlib.metadata as M, lerobot; print("v"+M.version("lerobot"), "->", lerobot.__file__)'
    if is_sel arx5;      then _VERIFY_LINES+=$'\n''pyarx|import importlib.metadata as M, pyarx; print("v"+M.version("pyarx"), "->", pyarx.__file__)'; fi
    if is_sel flexiv;    then _VERIFY_LINES+=$'\n''flexiv_rt|import importlib.metadata as M, flexiv_rt; print("v"+M.version("flexiv_rt"), "->", flexiv_rt.__file__)'; fi
    if is_sel pico4;     then _VERIFY_LINES+=$'\n''xensevr_pc_service_sdk|import importlib.metadata as M, xensevr_pc_service_sdk; print("v"+M.version("xensevr_pc_service_sdk"), "->", xensevr_pc_service_sdk.__file__)'; fi
    if is_sel xense;     then _VERIFY_LINES+=$'\n''xensesdk|import importlib.metadata as M, xensesdk; print("v"+M.version("xensesdk"), "->", xensesdk.__file__)'; fi
    if is_sel xense;     then _VERIFY_LINES+=$'\n''xgripper|import importlib.metadata as M, xgripper; print("v"+M.version("xgripper"), "->", xgripper.__file__)'; fi
    if is_sel xense;     then _VERIFY_LINES+=$'\n''xensesdk flash|from xensesdk.flash.linux_backend import LinuxFlashBackend; print("available" if LinuxFlashBackend().available else "NOT available")'; fi
    if is_sel taccap;    then _VERIFY_LINES+=$'\n''taccap-gripper|import importlib.metadata as M, xense.taccap; print("v"+M.version("taccap-gripper"), "->", xense.taccap.__file__)'; fi
    if is_sel elite;     then _VERIFY_LINES+=$'\n''elite_cs_sdk|import importlib.metadata as M, elite_cs_sdk; print("v"+M.version("elite_cs_sdk"), "->", elite_cs_sdk.__file__)'; fi
    if is_sel dynamixel; then _VERIFY_LINES+=$'\n''dynamixel_sdk|import importlib.metadata as M, dynamixel_sdk; print("v"+M.version("dynamixel_sdk"), "->", dynamixel_sdk.__file__)'; fi

    _VERIFY_FAIL=0
    while IFS='|' read -r _pkg _import; do
        [[ -z "$_pkg" ]] && continue
        _out="$(python -c "$_import" 2>&1)" && \
            echo "[OK]    $_pkg: $_out" || \
            { echo "[ERROR] $_pkg: $_out"; _VERIFY_FAIL=1; }
    done <<< "$_VERIFY_LINES"

    echo ""
    if [[ $_VERIFY_FAIL -eq 0 ]]; then
        echo "[INFO] All packages verified successfully."
    else
        echo "[ERROR] Some packages failed verification. Review the [ERROR] lines above."
    fi

    echo ""
    check_conda_uv_consistency

    echo ""
    echo "[INFO] Lerobot-Xense installation complete."
    exit $_VERIFY_FAIL
elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
    print_general_usage
    exit 0

else
    echo "Invalid argument."
    print_general_usage
    exit 1
fi
